global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Xunit;
global using Microsoft.Extensions.DependencyInjection;
global using Circuids.Pulse;
global using Circuids.Pulse.Extensions;
